FROM maven:3.6.3-jdk-11 as build
COPY src /usr/src/app/src
COPY pom.xml /usr/src/app
COPY lombok.config /usr/src/app
RUN mvn -f /usr/src/app/pom.xml clean package

FROM openjdk:11
COPY --from=build /usr/src/app/target/internship-application.jar /usr/app/internship-application.jar
EXPOSE 8080

CMD ["java","-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005","-Djava.security.egd=file:/dev/./urandom","-Dspring.profiles.active=dev","-jar","/usr/app/internship-application.jar"]

EXPOSE 5005