# Spring Framework properties
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  resources:
    add-mappings: false
  servlet:
    multipart:
      max-file-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: mailsender.internships@gmail.com
    password: swdjwnftpmjcqacn
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true

# Security properties
security:
  oauth2:
    resource:
      filter-order: 3

# Oauth20 properties
oauthData:
  clientId: internship
  clientSecret: $3cr3Tf0rD3Vpurp0$e$
  accessTokenValidity: 3600 # 1 hour
  refreshTokenValidity: 604800 # 7 days
  jwtSigningKey: jWtS3cR3tH1gHS3cur3d
  authorizedGrantTypes: password,refresh_token

# External source resource properties
resources:
  profileImagesDirectory: profile-images
  finalReportsDirectory: final-reports
