# Spring Framework properties
spring:
  datasource:
    url : 'jdbc:mysql://db:3306/internship-program?allowPublicKeyRetrieval=true&useSSL=false'
    username : '@dm1nUser11'
    password : 'us3rp@ssw0rD12'

# Cross origin resource sharing properties
cors:
  allowedOrigin: 'http://localhost:4300'

# External source resource properties
resources:
  environment-url: http://localhost:4300