# Spring Framework properties
spring:
  datasource:
    url : 'jdbc:mysql://localhost:3306/internship-program?allowPublicKeyRetrieval=true&useSSL=false'
    username : '@dm1nUser11'
    password : 'us3rp@ssw0rD12'